spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          # JWT URI，认证服务器IP，端口
          jwk-set-uri: 'http://10.20.54.133:10000/api/ztb-auth/anon/getPublicKey'

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      # id: 在所有路由定义中需要唯一，不能重复
      # uri: lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
      # predicates:- Path=/product/** ，规则为/product/** 的请求都还转发至微服务product-service中。
      routes:
        - id: ztb-auth
          uri: lb://ztb-auth
          predicates:
            - Path=/ztb-auth/**
          filters:
            - StripPrefix=1
            # 熔断降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultfallback'
        - id: ztb-biz
          uri: lb://ztb-biz
          predicates:
            - Path=/ztb-biz/**
          filters:
            - StripPrefix=1
            # 熔断降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultfallback'

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 10


#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 60000
  #请求连接的超时时间
  ConnectTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos/
    routes:
      - name: 认证服务
        serviceName: ztb-auth
        location: /v2/api-docs?group=default
        servicePath: /ztb-auth
      - name: 业务服务
        serviceName: ztb-biz
        location: /v2/api-docs?group=default
        servicePath: /ztb-biz

whitelist:
  urls: /**/anon/**, /webjars/**, /doc.html, /swagger-resources/**, /*/v2/api-docs
