spring:

    # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/ztb_manage_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    schema:
      - classpath:sql/dictionary.sql
      - classpath:sql/permissions.sql
      # - classpath:sql/administrative.sql
      - classpath:sql/schema.sql

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 10

swagger:
  base-packages: com.xdcplus.xdcweb.biz.controller

#knife4j配置
knife4j:
  #启用
  enable: true

mybatis-plus:
  type-aliases-package: com.xdcplus.xdcweb.biz.common.pojo.entity

