version: "3"

services:
  proxy:
    image: nginx:1.20.0
    container_name: proxy
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - ztb-biz
      - ztb-manage-web
    ports:
      - 9900:80
      - 9999:8081
      - 10000:8082
    volumes:
      - /data/ztb-manage/logs/proxy:/var/log/nginx
      - ./conf/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ztb_manage_net

  gateway:
    image: 10.20.54.132:8000/sc/gateway:latest
    container_name: gateway
    environment:
      ACTIVE_NAME: pro
    restart: always
    env_file:
      - ./conf/common/nacos.env
    expose:
      - 8080
    depends_on:
      - ztb-biz
    volumes:
      - /data/ztb-manage/logs/gateway:/logs
    networks:
      - ztb_manage_net

  ztb-biz:
    image: 10.20.54.132:8000/sc/ztb-biz:latest
    restart: always
    container_name: ztb-biz
    environment:
      ACTIVE_NAME: pro
      NACOS_HOST: 10.20.54.162
      NACOS_PORT: 8848
      MYSQL_HOST: 10.20.54.162
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ztb_biz
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: xdcplus.com
      REDIS_HOST: 10.20.54.162
      REDIS_PORT: 6379
      REDIS_DATABASE: 5
      MINIO_HOST: 10.20.54.162
      MINIO_PORT: 9000
      MINIO_BUCKET: ztb
      MINIO_USERNAME: minio
      MINIO_PASSWORD: minio123
      PCE_IP: 10.20.54.162
      IE_IP: 10.20.54.162
      PCE_PORT: 10000
      IE_PORT: 10000
    ports:
      - 9006:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-manage/logs/biz:/logs
    networks:
      - ztb_manage_net

  ztb-manage-web:
    image: 10.20.54.132:8000/sc/ztb-manage-web:latest
    container_name: ztb-manage-web
    environment:
      SEVER_HOST: http://10.20.54.162
      SEVER_PORT: 10000
      API_ZTB_PREFIX: /api/ztb
      API_INV_PREFIX: /api/inv
      API_IE_PREFIX: /api/ie
      API_PCE_PREFIX: /api/pce
      API_AUTH_PREFIX: /api/auth
    restart: always
    depends_on:
      - ztb-biz
    expose:
      - 80
    networks:
      - ztb_manage_net

  ztb-manage-portal:
    image: 10.20.54.132:8000/sc/ztb-manage-portal:latest
    container_name: ztb-manage-portal
    environment:
      SEVER_HOST: http://10.20.54.162
      SEVER_PORT: 10000
      API_ZTB_PREFIX: /api/ztb
      API_INV_PREFIX: /api/inv
      API_IE_PREFIX: /api/ie
      API_PCE_PREFIX: /api/pcv
      API_AUTH_PREFIX: /api/autv
    restart: always
    depends_on:
      - ztb-biz
    expose:
      - 8081
    networks:
      - ztb_manage_net

networks:
  ztb_manage_net:
    external: true

